[project]
name = "python-anything-applied"
version = "0.1.0"
description = "Applied version of python-anything"
readme = "README.md"
authors = [
    { name = "Ülgen Sarıkavak", email = "foss+python-anything@ulgenwanders.net" },
]
requires-python = ">=3.14"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "apache-airflow==3.1.7",
    "django==6.0.2",
    "fastapi==0.117.1",
    "langchain==1.2.9",
    "numpy==2.4.2",
    "pandas==3.0.0",
]

[dependency-groups]
dev = [
    # TODO:
    #   Find a way to define the following in this file:
    #   PYTHONBREAKPOINT = "ipdb.set_trace"
    "ipdb==0.13.13",
    "ipython==9.10.0",
    "mypy==1.16.1",
    "pytest==9.0.2",
    "pytest-xdist==3.8.0",
]

[tool.uv]
# The earliest version that supports the current lock file revision
required-version = ">=0.8.4"
package = false

[tool.pyproject-fmt]
indent = 4
keep_full_version = true
max_supported_python = "3.14"

[tool.pytest]
ini_options.testpaths = ["tests"]
ini_options.python_files = ["test_*.py"]
ini_options.python_classes = ["Test*"]
ini_options.python_functions = ["test_*"]
ini_options.addopts = ["-v", "--strict-markers", "--strict-config"]

[tool.mypy]
python_version = "3.14"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true
