# Adapted from https://docs.astral.sh/uv/guides/integration/github/#using-uv-in-github-actions

name: "Tests"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request: ~

permissions: {}

env:
  # renovate: datasource=python-version depName=python
  PYTHON_VERSION: 3.14.3
  # renovate: datasource=pypi depName=uv
  UV_VERSION: 0.10.9

concurrency:
  # GitHub doesn't allow accessing env here, so the value is duplicated to the job step.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: pytest -n auto
    runs-on: ubuntu-24.04
    timeout-minutes: 1

    steps:
      # GitHub Actions doesn't print the concurrency group in the logs.
      # This is to help debugging potential concurrency issues.
      # https://stackoverflow.com/questions/77571501/
      - name: Export concurrency key
        run: echo "concurrency-key=${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false

      - name: Install uv ${{ env.UV_VERSION }} & Python ${{ env.PYTHON_VERSION }}
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57  # v8.0.0
        with:
          enable-cache: true
          python-version: ${{ env.PYTHON_VERSION }}
          version: ${{ env.UV_VERSION }}

      - name: Install packages
        run: uv sync --frozen --no-install-project

      - name: Run tests
        working-directory: ./src
        run: uv run pytest -n auto
